task:
- name: stairway_room_exit
  type: waypoint_following
  waypoints:
  - {name: position-inset-point-0-to-stairway_room_exit-frame, x: 3.09, y: -9.79,
    yaw: 0, z: 0}
  - {name: position-inset-point-1-to-stairway_room_exit-frame, x: 1.2, y: -12.5, yaw: 0,
    z: 0}
  - {name: position-inset-point-2-to-stairway_room_exit-frame, x: -0.69, y: -11.18,
    yaw: 0, z: 0}
  - {name: position-inset-point-3-to-stairway_room_exit-frame, x: 1.21, y: -8.48,
    yaw: 0, z: 0}
