task:
- name: classroom_c025
  type: waypoint_following
  waypoints:
  - {x: 53.31, y: 37.6, yaw: 0, z: 0}
  - {x: 58.23, y: 34.16, yaw: 0, z: 0}
  - {x: 54.79, y: 29.24, yaw: 0, z: 0}
  - {x: 49.87, y: 32.69, yaw: 0, z: 0}
