task:
- name: classroom_c022
  type: waypoint_following
  waypoints:
  - {name: point-0-to-classroom_c022, x: 45.51, y: 36.05, yaw: 0, z: 0}
  - {name: point-1-to-classroom_c022, x: 40.6, y: 39.49, yaw: 0, z: 0}
  - {name: point-2-to-classroom_c022, x: 44.04, y: 44.4, yaw: 0, z: 0}
  - {name: point-3-to-classroom_c022, x: 48.95, y: 40.96, yaw: 0, z: 0}
