task:
- name: diagonal_corridor_right
  type: waypoint_following
  waypoints:
  - {id: iagonal_corridor_right-point-0, x: 45.52, y: 30.21, yaw: 0, z: 0}
  - {id: iagonal_corridor_right-point-1, x: 50.75, y: 28.3, yaw: 0, z: 0}
  - {id: iagonal_corridor_right-point-2, x: 49.98, y: 26.19, yaw: 0, z: 0}
  - {id: iagonal_corridor_right-point-3, x: 44.19, y: 28.3, yaw: 0, z: 0}
