task:
- name: left_short_connector
  type: waypoint_following
  waypoints:
  - {id: eft_short_connector-point-0, x: -20.65, y: 15.72, yaw: 0, z: 0}
  - {id: eft_short_connector-point-1, x: -7.56, y: 6.55, yaw: 0, z: 0}
  - {id: eft_short_connector-point-2, x: -9.49, y: 3.8, yaw: 0, z: 0}
  - {id: eft_short_connector-point-3, x: -22.58, y: 12.96, yaw: 0, z: 0}
