task:
- name: study_nook_left
  type: waypoint_following
  waypoints:
  - {id: tudy_nook_left-point-0, x: -16.25, y: 6.34, yaw: 0, z: 0}
  - {id: tudy_nook_left-point-1, x: -19.47, y: 1.75, yaw: 0, z: 0}
  - {id: tudy_nook_left-point-2, x: -19.96, y: 2.1, yaw: 0, z: 0}
  - {id: tudy_nook_left-point-3, x: -16.74, y: 6.68, yaw: 0, z: 0}
